name: Install packages
description: Setup node

inputs:
  working-directory:
    description: 'The working directory to run commands in'
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      working-directory: ${{ inputs.working-directory }}
      with:
        node-version-file: ".nvmrc"
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
