name: Deploy to Heroku via Git

on:
  push:
    branches: ["main", "heroku-deploy-new"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Login to Heroku
      - name: Login to Heroku
        run: |
          cat > ~/.netrc <<EOF
          machine api.heroku.com
            login ${{ secrets.HEROKU_EMAIL }}
            password ${{ secrets.HEROKU_API_KEY }}
          machine git.heroku.com
            login ${{ secrets.HEROKU_EMAIL }}
            password ${{ secrets.HEROKU_API_KEY }}
          EOF

      # Add Heroku remote
      - name: Add Heroku remote
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

      # Initialize git in backend directory if needed
      - name: Init git if needed
        run: |
          if [ ! -d .git ]; then
            git init
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Initial backend commit for Heroku deployment"
          fi

      # Push to Heroku
      - name: Push to Heroku
        run: |
          git push https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:main --force
