name: Deploy to Heroku

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      # If you need to deploy a specific directory instead of the entire repo
      # - name: Deploy Backend
      #   uses: akhileshns/heroku-deploy@v3.12.14
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}-backend
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
      #     appdir: "backend"

      # Add additional steps if you need to build your app before deploying
      # For example:
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build
      #   run: npm run build
