name: Deploy to Heroku via Git

on:
  push:
    branches: ["main", "heroku-deploy-new"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Login to Heroku
      - name: Login to Heroku
        run: |
          cat > ~/.netrc <<EOF
          machine api.heroku.com
            login ${{ secrets.HEROKU_EMAIL }}
            password ${{ secrets.HEROKU_API_KEY }}
          machine git.heroku.com
            login ${{ secrets.HEROKU_EMAIL }}
            password ${{ secrets.HEROKU_API_KEY }}
          EOF

      # Add Heroku remote
      - name: Add Heroku remote
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

      # Get current branch name and push to Heroku
      - name: Push to Heroku
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          CURRENT_BRANCH=$(git symbolic-ref --short HEAD || echo "HEAD")
          echo "Current branch is $CURRENT_BRANCH"
          git push heroku $CURRENT_BRANCH:main
